This project provides a sample application that uses the [[https://github.com/tnr-global/bishop][Bishop
framework]]. Bishop makes it much easier to provide an API for your
web-service that understands the HTTP semantics. This sample
application provides a simple web-service that lets you manage a to-do
list.

* Building the Application

  This application depends on snapshot builds of the Bishop framework,
  mostly because there isn’t anything /but/ snapshots available. What
  this means to you is that you also need to check out and install the
  Bishop library itself.

  #+BEGIN_SRC shell
  git clone git://github.com/tnr-global/bishop.git
  cd bishop
  lein install
  #+END_SRC

  With that done, you can checkout this project.

  #+BEGIN_SRC shell
  git clone git://github.com/tnr-global/bishop-sample.git
  cd bishop-sample
  #+END_SRC

  But don’t build it yet! You’ll need to tell Leiningen that you’re
  okay using snapshots of dependent libraries.

  #+BEGIN_SRC shell
  export LEIN_SNAPSHOTS_IN_RELEASE=true
  lein uberjar
  ...watch Leiningen build...
  java -jar bishop-sample-1.0-standalone.jar
  #+END_SRC

* Sample Transactions

  Once you have the application built and running, it will respond to
  the standard created, update and delete requests. Examples of these
  requests are detailed below.

** Listing All To-Do Items

   #+BEGIN_SRC shell
   $ curl -i http://localhost:3000/todos
   HTTP/1.1 200 OK
   Date: Sun, 06 May 2012 15:03:54 GMT
   Vary: accept
   Last-Modified: Sun, 06 May 2012 15:03:52 UTC
   Content-Length: 133
   Server: Jetty(6.1.x)

   [{"_links":{"self":"todos/1"},"id":1,"title":"Your first to-do",
   "description":"Write more to-dos!","created":"2012-05-06T15:03:52Z"}]
   #+END_SRC

** Updating a To-Do Item

   #+BEGIN_SRC shell
   $ curl -v http://localhost:3000/todos/1 -H 'Content-Type: application/json' \
     -XPUT -d '{
      "title" : "More creative writing",
       "description" : "Write more blog posts"}'

   HTTP/1.1 200 OK
   Date: Sun, 06 May 2012 15:13:21 GMT
   Vary: accept
   Content-Length: 141
   Server: Jetty(6.1.x)

   {"_links":{"self":"todos/1/1"},"id":1,"title":"More creative writing",
   "description":"Write more blog posts","created":"2012-05-06T15:03:52Z"}
   #+END_SRC

** Adding A New To-Do Item

   #+BEGIN_SRC shell
   $ curl -i http://localhost:3000/todos -H 'Content-Type: application/json' \
     -XPOST -d '{
      "title" : "Work on web service",
      "description" : "Work on your web service error handling"}'

   HTTP/1.1 303 See Other
   Date: Sun, 06 May 2012 15:06:53 GMT
   Vary: accept
   Location: todos/2
   Debug: N11, switching to PUT
   Content-Length: 0
   Server: Jetty(6.1.x)
   #+END_SRC

** Retrieving a To-Do Item

   #+BEGIN_SRC shell
   $ curl -i http://localhost:3000/todos/2

   HTTP/1.1 200 OK
   Date: Sun, 06 May 2012 15:08:57 GMT
   Vary: accept
   ETag: "1336316813540-2"
   Last-Modified: Sun, 06 May 2012 15:06:53 UTC
   Content-Length: 157
   Server: Jetty(6.1.x)
   #+END_SRC

** Deleting a To-Do Item

   #+BEGIN_SRC shell
   $ curl -i http://localhost:3000/todos/2 -XDELETE

   HTTP/1.1 204 No Content
   Date: Sun, 06 May 2012 15:11:01 GMT
   Vary: accept
   Server: Jetty(6.1.x)
   #+END_SRC
